export default {
    tagStart: /<([\w]+)>/g,
    tagEnd: /<\/>/g,
    tagSeparator: "*",
    text: [
        "<TEXT>" +
        "<DEFAULT_KEYWORD>public</> <DEFAULT_KEYWORD>class</> <DEFAULT_CLASS_NAME>Demo</> <DEFAULT_BRACES>{</>",
        "  <DEFAULT_KEYWORD>private</> <DEFAULT_KEYWORD>static</> <DEFAULT_KEYWORD>final</> <DEFAULT_CLASS_REFERENCE>String</> <DEFAULT_CONSTANT>CONSTANT</> <DEFAULT_OPERATION_SIGN>=</> <DEFAULT_STRING>\"String\"</><DEFAULT_SEMICOLON>;</>",
        "  <DEFAULT_KEYWORD>private</> <DEFAULT_CLASS_REFERENCE>Object</> <DEFAULT_INSTANCE_FIELD>o</><DEFAULT_SEMICOLON>;</>",
        "  <DEFAULT_DOC_COMMENT>/**</>",
        "   <DEFAULT_DOC_COMMENT>* Creates a new demo.</>",
        "   <DEFAULT_DOC_COMMENT>* <DEFAULT_DOC_COMMENT_TAG>@param</> o The object to demonstrate.</>",
        "   <DEFAULT_DOC_COMMENT>*/</>",
        "  <DEFAULT_KEYWORD>public</> <DEFAULT_FUNCTION_DECLARATION>Demo</><DEFAULT_PARENTHS>(</><DEFAULT_CLASS_REFERENCE>Object</> <DEFAULT_PARAMETER>o</><DEFAULT_PARENTHS>)</> <DEFAULT_BRACES>{</>",
        "    <DEFAULT_KEYWORD>this</><DEFAULT_OPERATION_SIGN>.</><DEFAULT_INSTANCE_FIELD>o</> <DEFAULT_OPERATION_SIGN>=</> <DEFAULT_PARAMETER>o</><DEFAULT_SEMICOLON>;</>",
        "    <DEFAULT_CLASS_REFERENCE>String</> <DEFAULT_LOCAL_VARIABLE>s</> <DEFAULT_OPERATION_SIGN>=</> <DEFAULT_CONSTANT>CONSTANT</> <DEFAULT_OPERATION_SIGN>+</> <DEFAULT_STRING>\"Other\"</><DEFAULT_SEMICOLON>;</>",
        "    <DEFAULT_KEYWORD>int</> <DEFAULT_LOCAL_VARIABLE>i</> <DEFAULT_OPERATION_SIGN>=</> <DEFAULT_NUMBER>123</><DEFAULT_SEMICOLON>;</>",
        "  <DEFAULT_BRACES>}</>",
        "  <DEFAULT_KEYWORD>public</> <DEFAULT_KEYWORD>static</> <DEFAULT_KEYWORD>void</> <DEFAULT_FUNCTION_DECLARATION>main</><DEFAULT_PARENTHS>(</><DEFAULT_CLASS_REFERENCE>String</><DEFAULT_BRACKETS>[]</> <DEFAULT_PARAMETER>args</><DEFAULT_PARENTHS>)</> <DEFAULT_BRACES>{</>",
        "    <DEFAULT_FUNCTION_DECLARATION>Demo</> <DEFAULT_LOCAL_VARIABLE>demo</> = <DEFAULT_KEYWORD>new</> <DEFAULT_FUNCTION_DECLARATION>Demo</><DEFAULT_PARENTHS>()</><DEFAULT_SEMICOLON>;</>",
        "  <DEFAULT_BRACES>}</>",
        "<DEFAULT_BRACES>}</>",
        "</>"
    ].join("\n")
}
