export default {
    tagStart: /<([\w]+)>/g,
    tagEnd: /<\/>/g,
    text: [
        "<TEXT>" +
        "<RUBY_SPECIFIC_CALL>require</> <RUBY_STRING>\"test\"</>",
        "<RUBY_CONSTANT>CONSTANT</> <RUBY_OPERATION_SIGN>=</> <RUBY_NUMBER>777</>",
        "",
        "<RUBY_COMMENT># Sample comment</>",
        "",
        "<RUBY_KEYWORD>class</> <RUBY_CONSTANT>Module</><RUBY_COLON>::</><RUBY_CONSTANT>Class</>",
        "  <RUBY_SPECIFIC_CALL>include</> <RUBY_CONSTANT>Testcase</>",
        "",
        "  <RUBY_PARAMDEF_CALL>render</> <RUBY_SYMBOL>:action</> <RUBY_HASH_ASSOC>=></> <RUBY_STRING>\'foo\'</>",
        "  <RUBY_KEYWORD>def</> <RUBY_METHOD_NAME>foo</><RUBY_PARENTHESES>(</><RUBY_PARAMETER_ID>parameter</><RUBY_PARENTHESES>)</>",
        "    <RUBY_IVAR>@parameter</> <RUBY_OPERATION_SIGN>=</> <RUBY_PARAMETER_ID>parameter</>",
        "  <RUBY_KEYWORD>end</>",
        "",
        "  <RUBY_LOCAL_VAR_ID>local_var</> <RUBY_OPERATION_SIGN>=</> <RUBY_IDENTIFIER>eval</> <RUBY_HEREDOC_ID><<-\"FOO\"</><RUBY_SEMICOLON>;</><RUBY_LINE_CONTINUATION>\\</>",
        "  <RUBY_IDENTIFIER>printIndex</> <RUBY_STRING>\"Hello world!\"</>",
        "  <RUBY_HEREDOC_CONTENT>And now this is heredoc!",
        "  printIndex \"Hello world again!\"</>",
        "  <RUBY_HEREDOC_ID>FOO</>",
        "  <RUBY_IDENTIFIER>foo</><RUBY_PARENTHESES>(</><RUBY_INTERPOLATED_STRING>\"<RUBY_EXPR_IN_STRING>#{</><RUBY_GVAR>$GLOBAL_TIME</> <RUBY_OPERATION_SIGN>>></> <RUBY_NTH_REF>$`</><RUBY_EXPR_IN_STRING>}</> is <RUBY_INVALID_ESCAPE_SEQUENCE>\\Z</> sample \\\"string\\\"\"</> <RUBY_OPERATION_SIGN>*</> <RUBY_NUMBER>777</><RUBY_PARENTHESES>)</><RUBY_SEMICOLON>;</>",
        "  <RUBY_KEYWORD>if</> <RUBY_PARENTHESES>(</><RUBY_NTH_REF>$1</> <RUBY_OPERATION_SIGN>=~</> <RUBY_REGEXP>/sample regular expression/ni</><RUBY_PARENTHESES>)</> <RUBY_KEYWORD>then</>",
        "  <RUBY_KEYWORD>begin</>",
        "    <RUBY_IDENTIFIER>puts</> <RUBY_WORDS>%W(sample words)</><RUBY_COLON>,</> <RUBY_CONSTANT>CONSTANT</><RUBY_COLON>,</> <RUBY_SYMBOL>:fooo</><RUBY_SEMICOLON>;</>",
        "    <RUBY_IDENTIFIER>do_something</> <RUBY_SYMBOL>:action</> <RUBY_HASH_ASSOC>=></> <RUBY_STRING>\"action\"</>",
        "  <RUBY_KEYWORD>end</>",
        "  <RUBY_IDENTIFIER>expect</><RUBY_BRACES>{</><RUBY_IDENTIFIER>counter</><RUBY_BRACKETS>[</><RUBY_NUMBER>0</><RUBY_BRACKETS>]</><RUBY_BRACES>}</><RUBY_DOT>.</><RUBY_IDENTIFIER>to_be</> <RUBY_IDENTIFIER>eq</> <RUBY_NUMBER>1</>",
        "  <RUBY_NUMBER>1</><RUBY_DOT>.</><RUBY_IDENTIFIER>upto</><RUBY_PARENTHESES>(</><RUBY_CVAR>@@n</><RUBY_PARENTHESES>)</> <RUBY_KEYWORD>do</> <RUBY_OPERATION_SIGN>|</><RUBY_PARAMETER_ID>index</><RUBY_OPERATION_SIGN>|</> <RUBY_IDENTIFIER>printIndex</> <RUBY_STRING>\'Hello\'</> <RUBY_OPERATION_SIGN>+</> <RUBY_PARAMETER_ID>index</> <RUBY_KEYWORD>end</>",
        "  <RUBY_BAD_CHARACTER>\\\\\\\\\\\\\\\\\\\</><RUBY_LINE_CONTINUATION>\</>",
        "  <RUBY_KEYWORD>end</>",
        "<RUBY_KEYWORD>end</>",
        "</>"
    ].join("\n"),
    fallback: {
        "RUBY_BRACES": ["DEFAULT_BRACES"],
        "RUBY_BRACKETS": ["DEFAULT_BRACKETS"],
        "RUBY_COLON": ["DEFAULT_DOT"],
        "RUBY_COMMA": ["DEFAULT_COMMA"],
        "RUBY_COMMENT": ["DEFAULT_DOC_COMMENT"],
        "RUBY_CONSTANT": ["DEFAULT_CONSTANT"],
        "RUBY_CONSTANT_DECLARATION": ["DEFAULT_CONSTANT"],
        "RUBY_CVAR": ["DEFAULT_STATIC_FIELD"],
        "RUBY_DOT": ["DEFAULT_DOT"],
        "RUBY_ESCAPE_SEQUENCE": ["DEFAULT_VALID_STRING_ESCAPE"],
        "RUBY_EXPR_IN_STRING": ["DEFAULT_STRING"],
        "RUBY_GVAR": ["DEFAULT_GLOBAL_VARIABLE"],
        "RUBY_HASH_ASSOC": ["DEFAULT_OPERATION_SIGN"],
        "RUBY_HEREDOC_CONTENT": ["TEXT"],
        "RUBY_HEREDOC_ID": ["DEFAULT_IDENTIFIER"],
        "RUBY_IDENTIFIER": ["DEFAULT_IDENTIFIER"],
        "RUBY_INTERPOLATED_STRING": ["DEFAULT_STRING"],
        "RUBY_INVALID_ESCAPE_SEQUENCE": ["DEFAULT_INVALID_STRING_ESCAPE"],
        "RUBY_IVAR": ["DEFAULT_INSTANCE_FIELD"],
        "RUBY_KEYWORD": ["DEFAULT_KEYWORD"],
        "RUBY_LINE_CONTINUATION": ["DEFAULT_COMMA"],
        "RUBY_LOCAL_VAR_ID": ["DEFAULT_LOCAL_VARIABLE"],
        "RUBY_METHOD_NAME": ["DEFAULT_INSTANCE_METHOD"],
        "RUBY_NTH_REF": ["DEFAULT_PREDEFINED_SYMBOL"],
        "RUBY_NUMBER": ["DEFAULT_NUMBER"],
        "RUBY_OPERATION_SIGN": ["DEFAULT_OPERATION_SIGN"],
        "RUBY_PARAMDEF_CALL": ["DEFAULT_STATIC_METHOD"],
        "RUBY_PARAMETER_ID": ["DEFAULT_PARAMETER"],
        "RUBY_PARENTHESES": ["DEFAULT_PARENTHS"],
        "RUBY_REGEXP": ["DEFAULT_TEMPLATE_LANGUAGE_COLOR"],
        "RUBY_SEMICOLON": ["DEFAULT_SEMICOLON"],
        "RUBY_SPECIFIC_CALL": ["DEFAULT_STATIC_METHOD"],
        "RUBY_STRING": ["DEFAULT_STRING"],
        "RUBY_SYMBOL": ["DEFAULT_INSTANCE_FIELD"],
        "RUBY_WORDS": ["DEFAULT_STRING"]
    }
}
